% -------------------------------------------------------------------
%  Generated by MATLAB on 4-Jun-2017 23:24:37
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('a2.mat');

Age = [38; 43; 38; 40; 49; 46; 33; 40; 28; 31; 45; 42; 25; 39; 36; 48; ...
       32; 27; 37; 50; 48; 39; 41; 44; 28; 25; 39; 25; 36; 30; 45; 40; ...
       25; 47; 44; 48; 44; 35; 33; 38; 39; 44; 44; 37; 45; 37; 30; 39; ...
       42; 42; 49; 44; 43; 47; 50; 38; 41; 45; 36; 38; 29; 28; 30; 28; ...
       29; 36; 45; 32; 31; 48; 25; 40; 39; 41; 33; 31; 35; 32; 42; 48; ...
       34; 39; 28; 29; 32; 39; 37; 49; 31; 37; 38; 45; 30; 48; 48; 25; ...
       44; 49; 45; 48];

Diastolic = [93; 77; 83; 75; 80; 70; 88; 82; 78; 86; 77; 68; 74; 95; 79; ...
             92; 95; 79; 77; 76; 75; 79; 88; 90; 96; 77; 80; 76; 83; 89; ...
             92; 83; 80; 84; 92; 83; 90; 85; 90; 74; 92; 80; 89; 96; 89; ...
             77; 81; 76; 83; 78; 95; 91; 91; 86; 89; 79; 74; 82; 76; 81; ...
             77; 73; 85; 76; 80; 80; 79; 82; 79; 82; 75; 91; 74; 78; 85; ...
             84; 75; 78; 81; 79; 85; 79; 82; 80; 80; 92; 92; 96; 87; 81; ...
             90; 77; 91; 79; 73; 99; 92; 74; 93; 86];

Gender = cell(100, 1);
Gender{1,1} = 'Male';
Gender{2,1} = 'Male';
Gender{3,1} = 'Female';
Gender{4,1} = 'Female';
Gender{5,1} = 'Female';
Gender{6,1} = 'Female';
Gender{7,1} = 'Female';
Gender{8,1} = 'Male';
Gender{9,1} = 'Male';
Gender{10,1} = 'Female';
Gender{11,1} = 'Female';
Gender{12,1} = 'Female';
Gender{13,1} = 'Male';
Gender{14,1} = 'Male';
Gender{15,1} = 'Female';
Gender{16,1} = 'Male';
Gender{17,1} = 'Male';
Gender{18,1} = 'Female';
Gender{19,1} = 'Male';
Gender{20,1} = 'Male';
Gender{21,1} = 'Female';
Gender{22,1} = 'Female';
Gender{23,1} = 'Female';
Gender{24,1} = 'Female';
Gender{25,1} = 'Female';
Gender{26,1} = 'Male';
Gender{27,1} = 'Female';
Gender{28,1} = 'Female';
Gender{29,1} = 'Male';
Gender{30,1} = 'Male';
Gender{31,1} = 'Female';
Gender{32,1} = 'Female';
Gender{33,1} = 'Female';
Gender{34,1} = 'Male';
Gender{35,1} = 'Male';
Gender{36,1} = 'Female';
Gender{37,1} = 'Male';
Gender{38,1} = 'Female';
Gender{39,1} = 'Male';
Gender{40,1} = 'Female';
Gender{41,1} = 'Male';
Gender{42,1} = 'Male';
Gender{43,1} = 'Male';
Gender{44,1} = 'Male';
Gender{45,1} = 'Male';
Gender{46,1} = 'Female';
Gender{47,1} = 'Male';
Gender{48,1} = 'Female';
Gender{49,1} = 'Male';
Gender{50,1} = 'Male';
Gender{51,1} = 'Male';
Gender{52,1} = 'Female';
Gender{53,1} = 'Female';
Gender{54,1} = 'Female';
Gender{55,1} = 'Male';
Gender{56,1} = 'Female';
Gender{57,1} = 'Female';
Gender{58,1} = 'Male';
Gender{59,1} = 'Male';
Gender{60,1} = 'Female';
Gender{61,1} = 'Female';
Gender{62,1} = 'Female';
Gender{63,1} = 'Female';
Gender{64,1} = 'Female';
Gender{65,1} = 'Female';
Gender{66,1} = 'Male';
Gender{67,1} = 'Female';
Gender{68,1} = 'Female';
Gender{69,1} = 'Female';
Gender{70,1} = 'Female';
Gender{71,1} = 'Male';
Gender{72,1} = 'Female';
Gender{73,1} = 'Male';
Gender{74,1} = 'Female';
Gender{75,1} = 'Female';
Gender{76,1} = 'Male';
Gender{77,1} = 'Female';
Gender{78,1} = 'Male';
Gender{79,1} = 'Male';
Gender{80,1} = 'Female';
Gender{81,1} = 'Male';
Gender{82,1} = 'Male';
Gender{83,1} = 'Male';
Gender{84,1} = 'Female';
Gender{85,1} = 'Female';
Gender{86,1} = 'Male';
Gender{87,1} = 'Female';
Gender{88,1} = 'Female';
Gender{89,1} = 'Female';
Gender{90,1} = 'Female';
Gender{91,1} = 'Male';
Gender{92,1} = 'Male';
Gender{93,1} = 'Female';
Gender{94,1} = 'Male';
Gender{95,1} = 'Female';
Gender{96,1} = 'Male';
Gender{97,1} = 'Male';
Gender{98,1} = 'Male';
Gender{99,1} = 'Male';
Gender{100,1} = 'Male';

Height = [71; 69; 64; 67; 64; 68; 64; 68; 68; 66; 68; 66; 71; 72; 65; 71; ...
          69; 69; 70; 68; 65; 64; 62; 66; 65; 70; 63; 63; 68; 67; 70; 66; ...
          64; 70; 71; 66; 71; 66; 66; 63; 71; 69; 70; 70; 67; 65; 68; 62; ...
          70; 67; 68; 62; 64; 66; 72; 63; 66; 70; 71; 68; 63; 65; 67; 66; ...
          68; 71; 70; 60; 64; 64; 66; 64; 72; 65; 67; 72; 64; 68; 66; 64; ...
          68; 69; 69; 64; 63; 68; 65; 63; 66; 65; 68; 71; 70; 71; 66; 69; ...
          69; 70; 68; 66];

LRModel = saveVarsMat.LRModel; % <1x1 LinearModel> unsupported class

LRModel2 = saveVarsMat.LRModel2; % <1x1 LinearModel> unsupported class

LastName = cell(100, 1);
LastName{1,1} = 'Smith';
LastName{2,1} = 'Johnson';
LastName{3,1} = 'Williams';
LastName{4,1} = 'Jones';
LastName{5,1} = 'Brown';
LastName{6,1} = 'Davis';
LastName{7,1} = 'Miller';
LastName{8,1} = 'Wilson';
LastName{9,1} = 'Moore';
LastName{10,1} = 'Taylor';
LastName{11,1} = 'Anderson';
LastName{12,1} = 'Thomas';
LastName{13,1} = 'Jackson';
LastName{14,1} = 'White';
LastName{15,1} = 'Harris';
LastName{16,1} = 'Martin';
LastName{17,1} = 'Thompson';
LastName{18,1} = 'Garcia';
LastName{19,1} = 'Martinez';
LastName{20,1} = 'Robinson';
LastName{21,1} = 'Clark';
LastName{22,1} = 'Rodriguez';
LastName{23,1} = 'Lewis';
LastName{24,1} = 'Lee';
LastName{25,1} = 'Walker';
LastName{26,1} = 'Hall';
LastName{27,1} = 'Allen';
LastName{28,1} = 'Young';
LastName{29,1} = 'Hernandez';
LastName{30,1} = 'King';
LastName{31,1} = 'Wright';
LastName{32,1} = 'Lopez';
LastName{33,1} = 'Hill';
LastName{34,1} = 'Scott';
LastName{35,1} = 'Green';
LastName{36,1} = 'Adams';
LastName{37,1} = 'Baker';
LastName{38,1} = 'Gonzalez';
LastName{39,1} = 'Nelson';
LastName{40,1} = 'Carter';
LastName{41,1} = 'Mitchell';
LastName{42,1} = 'Perez';
LastName{43,1} = 'Roberts';
LastName{44,1} = 'Turner';
LastName{45,1} = 'Phillips';
LastName{46,1} = 'Campbell';
LastName{47,1} = 'Parker';
LastName{48,1} = 'Evans';
LastName{49,1} = 'Edwards';
LastName{50,1} = 'Collins';
LastName{51,1} = 'Stewart';
LastName{52,1} = 'Sanchez';
LastName{53,1} = 'Morris';
LastName{54,1} = 'Rogers';
LastName{55,1} = 'Reed';
LastName{56,1} = 'Cook';
LastName{57,1} = 'Morgan';
LastName{58,1} = 'Bell';
LastName{59,1} = 'Murphy';
LastName{60,1} = 'Bailey';
LastName{61,1} = 'Rivera';
LastName{62,1} = 'Cooper';
LastName{63,1} = 'Richardson';
LastName{64,1} = 'Cox';
LastName{65,1} = 'Howard';
LastName{66,1} = 'Ward';
LastName{67,1} = 'Torres';
LastName{68,1} = 'Peterson';
LastName{69,1} = 'Gray';
LastName{70,1} = 'Ramirez';
LastName{71,1} = 'James';
LastName{72,1} = 'Watson';
LastName{73,1} = 'Brooks';
LastName{74,1} = 'Kelly';
LastName{75,1} = 'Sanders';
LastName{76,1} = 'Price';
LastName{77,1} = 'Bennett';
LastName{78,1} = 'Wood';
LastName{79,1} = 'Barnes';
LastName{80,1} = 'Ross';
LastName{81,1} = 'Henderson';
LastName{82,1} = 'Coleman';
LastName{83,1} = 'Jenkins';
LastName{84,1} = 'Perry';
LastName{85,1} = 'Powell';
LastName{86,1} = 'Long';
LastName{87,1} = 'Patterson';
LastName{88,1} = 'Hughes';
LastName{89,1} = 'Flores';
LastName{90,1} = 'Washington';
LastName{91,1} = 'Butler';
LastName{92,1} = 'Simmons';
LastName{93,1} = 'Foster';
LastName{94,1} = 'Gonzales';
LastName{95,1} = 'Bryant';
LastName{96,1} = 'Alexander';
LastName{97,1} = 'Russell';
LastName{98,1} = 'Griffin';
LastName{99,1} = 'Diaz';
LastName{100,1} = 'Hayes';

Location = cell(100, 1);
Location{1,1} = 'County General Hospital';
Location{2,1} = 'VA Hospital';
Location{3,1} = 'St. Mary''s Medical Center';
Location{4,1} = 'VA Hospital';
Location{5,1} = 'County General Hospital';
Location{6,1} = 'St. Mary''s Medical Center';
Location{7,1} = 'VA Hospital';
Location{8,1} = 'VA Hospital';
Location{9,1} = 'St. Mary''s Medical Center';
Location{10,1} = 'County General Hospital';
Location{11,1} = 'County General Hospital';
Location{12,1} = 'St. Mary''s Medical Center';
Location{13,1} = 'VA Hospital';
Location{14,1} = 'VA Hospital';
Location{15,1} = 'St. Mary''s Medical Center';
Location{16,1} = 'VA Hospital';
Location{17,1} = 'St. Mary''s Medical Center';
Location{18,1} = 'VA Hospital';
Location{19,1} = 'County General Hospital';
Location{20,1} = 'County General Hospital';
Location{21,1} = 'VA Hospital';
Location{22,1} = 'VA Hospital';
Location{23,1} = 'VA Hospital';
Location{24,1} = 'County General Hospital';
Location{25,1} = 'County General Hospital';
Location{26,1} = 'VA Hospital';
Location{27,1} = 'VA Hospital';
Location{28,1} = 'County General Hospital';
Location{29,1} = 'County General Hospital';
Location{30,1} = 'County General Hospital';
Location{31,1} = 'VA Hospital';
Location{32,1} = 'VA Hospital';
Location{33,1} = 'St. Mary''s Medical Center';
Location{34,1} = 'St. Mary''s Medical Center';
Location{35,1} = 'County General Hospital';
Location{36,1} = 'VA Hospital';
Location{37,1} = 'VA Hospital';
Location{38,1} = 'St. Mary''s Medical Center';
Location{39,1} = 'St. Mary''s Medical Center';
Location{40,1} = 'St. Mary''s Medical Center';
Location{41,1} = 'County General Hospital';
Location{42,1} = 'VA Hospital';
Location{43,1} = 'VA Hospital';
Location{44,1} = 'VA Hospital';
Location{45,1} = 'VA Hospital';
Location{46,1} = 'County General Hospital';
Location{47,1} = 'VA Hospital';
Location{48,1} = 'County General Hospital';
Location{49,1} = 'County General Hospital';
Location{50,1} = 'County General Hospital';
Location{51,1} = 'County General Hospital';
Location{52,1} = 'St. Mary''s Medical Center';
Location{53,1} = 'County General Hospital';
Location{54,1} = 'VA Hospital';
Location{55,1} = 'VA Hospital';
Location{56,1} = 'VA Hospital';
Location{57,1} = 'St. Mary''s Medical Center';
Location{58,1} = 'St. Mary''s Medical Center';
Location{59,1} = 'VA Hospital';
Location{60,1} = 'St. Mary''s Medical Center';
Location{61,1} = 'County General Hospital';
Location{62,1} = 'VA Hospital';
Location{63,1} = 'County General Hospital';
Location{64,1} = 'County General Hospital';
Location{65,1} = 'VA Hospital';
Location{66,1} = 'St. Mary''s Medical Center';
Location{67,1} = 'County General Hospital';
Location{68,1} = 'County General Hospital';
Location{69,1} = 'VA Hospital';
Location{70,1} = 'County General Hospital';
Location{71,1} = 'County General Hospital';
Location{72,1} = 'VA Hospital';
Location{73,1} = 'St. Mary''s Medical Center';
Location{74,1} = 'St. Mary''s Medical Center';
Location{75,1} = 'St. Mary''s Medical Center';
Location{76,1} = 'VA Hospital';
Location{77,1} = 'County General Hospital';
Location{78,1} = 'St. Mary''s Medical Center';
Location{79,1} = 'County General Hospital';
Location{80,1} = 'VA Hospital';
Location{81,1} = 'St. Mary''s Medical Center';
Location{82,1} = 'VA Hospital';
Location{83,1} = 'County General Hospital';
Location{84,1} = 'St. Mary''s Medical Center';
Location{85,1} = 'VA Hospital';
Location{86,1} = 'County General Hospital';
Location{87,1} = 'County General Hospital';
Location{88,1} = 'County General Hospital';
Location{89,1} = 'VA Hospital';
Location{90,1} = 'St. Mary''s Medical Center';
Location{91,1} = 'County General Hospital';
Location{92,1} = 'VA Hospital';
Location{93,1} = 'St. Mary''s Medical Center';
Location{94,1} = 'County General Hospital';
Location{95,1} = 'County General Hospital';
Location{96,1} = 'County General Hospital';
Location{97,1} = 'VA Hospital';
Location{98,1} = 'County General Hospital';
Location{99,1} = 'County General Hospital';
Location{100,1} = 'County General Hospital';

Patient_data = saveVarsMat.Patient_data; % <1x1 table> unsupported class

SelfAssessedHealthStatus = cell(100, 1);
SelfAssessedHealthStatus{1,1} = 'Excellent';
SelfAssessedHealthStatus{2,1} = 'Fair';
SelfAssessedHealthStatus{3,1} = 'Good';
SelfAssessedHealthStatus{4,1} = 'Fair';
SelfAssessedHealthStatus{5,1} = 'Good';
SelfAssessedHealthStatus{6,1} = 'Good';
SelfAssessedHealthStatus{7,1} = 'Good';
SelfAssessedHealthStatus{8,1} = 'Good';
SelfAssessedHealthStatus{9,1} = 'Excellent';
SelfAssessedHealthStatus{10,1} = 'Excellent';
SelfAssessedHealthStatus{11,1} = 'Excellent';
SelfAssessedHealthStatus{12,1} = 'Poor';
SelfAssessedHealthStatus{13,1} = 'Poor';
SelfAssessedHealthStatus{14,1} = 'Excellent';
SelfAssessedHealthStatus{15,1} = 'Good';
SelfAssessedHealthStatus{16,1} = 'Good';
SelfAssessedHealthStatus{17,1} = 'Excellent';
SelfAssessedHealthStatus{18,1} = 'Fair';
SelfAssessedHealthStatus{19,1} = 'Good';
SelfAssessedHealthStatus{20,1} = 'Good';
SelfAssessedHealthStatus{21,1} = 'Excellent';
SelfAssessedHealthStatus{22,1} = 'Fair';
SelfAssessedHealthStatus{23,1} = 'Fair';
SelfAssessedHealthStatus{24,1} = 'Fair';
SelfAssessedHealthStatus{25,1} = 'Good';
SelfAssessedHealthStatus{26,1} = 'Poor';
SelfAssessedHealthStatus{27,1} = 'Excellent';
SelfAssessedHealthStatus{28,1} = 'Good';
SelfAssessedHealthStatus{29,1} = 'Poor';
SelfAssessedHealthStatus{30,1} = 'Excellent';
SelfAssessedHealthStatus{31,1} = 'Excellent';
SelfAssessedHealthStatus{32,1} = 'Poor';
SelfAssessedHealthStatus{33,1} = 'Excellent';
SelfAssessedHealthStatus{34,1} = 'Excellent';
SelfAssessedHealthStatus{35,1} = 'Good';
SelfAssessedHealthStatus{36,1} = 'Excellent';
SelfAssessedHealthStatus{37,1} = 'Good';
SelfAssessedHealthStatus{38,1} = 'Fair';
SelfAssessedHealthStatus{39,1} = 'Good';
SelfAssessedHealthStatus{40,1} = 'Good';
SelfAssessedHealthStatus{41,1} = 'Fair';
SelfAssessedHealthStatus{42,1} = 'Excellent';
SelfAssessedHealthStatus{43,1} = 'Good';
SelfAssessedHealthStatus{44,1} = 'Excellent';
SelfAssessedHealthStatus{45,1} = 'Good';
SelfAssessedHealthStatus{46,1} = 'Fair';
SelfAssessedHealthStatus{47,1} = 'Poor';
SelfAssessedHealthStatus{48,1} = 'Good';
SelfAssessedHealthStatus{49,1} = 'Excellent';
SelfAssessedHealthStatus{50,1} = 'Good';
SelfAssessedHealthStatus{51,1} = 'Poor';
SelfAssessedHealthStatus{52,1} = 'Good';
SelfAssessedHealthStatus{53,1} = 'Poor';
SelfAssessedHealthStatus{54,1} = 'Excellent';
SelfAssessedHealthStatus{55,1} = 'Excellent';
SelfAssessedHealthStatus{56,1} = 'Excellent';
SelfAssessedHealthStatus{57,1} = 'Good';
SelfAssessedHealthStatus{58,1} = 'Good';
SelfAssessedHealthStatus{59,1} = 'Good';
SelfAssessedHealthStatus{60,1} = 'Good';
SelfAssessedHealthStatus{61,1} = 'Excellent';
SelfAssessedHealthStatus{62,1} = 'Good';
SelfAssessedHealthStatus{63,1} = 'Excellent';
SelfAssessedHealthStatus{64,1} = 'Good';
SelfAssessedHealthStatus{65,1} = 'Excellent';
SelfAssessedHealthStatus{66,1} = 'Good';
SelfAssessedHealthStatus{67,1} = 'Excellent';
SelfAssessedHealthStatus{68,1} = 'Excellent';
SelfAssessedHealthStatus{69,1} = 'Excellent';
SelfAssessedHealthStatus{70,1} = 'Excellent';
SelfAssessedHealthStatus{71,1} = 'Good';
SelfAssessedHealthStatus{72,1} = 'Fair';
SelfAssessedHealthStatus{73,1} = 'Excellent';
SelfAssessedHealthStatus{74,1} = 'Poor';
SelfAssessedHealthStatus{75,1} = 'Excellent';
SelfAssessedHealthStatus{76,1} = 'Fair';
SelfAssessedHealthStatus{77,1} = 'Fair';
SelfAssessedHealthStatus{78,1} = 'Poor';
SelfAssessedHealthStatus{79,1} = 'Excellent';
SelfAssessedHealthStatus{80,1} = 'Good';
SelfAssessedHealthStatus{81,1} = 'Good';
SelfAssessedHealthStatus{82,1} = 'Excellent';
SelfAssessedHealthStatus{83,1} = 'Good';
SelfAssessedHealthStatus{84,1} = 'Good';
SelfAssessedHealthStatus{85,1} = 'Excellent';
SelfAssessedHealthStatus{86,1} = 'Good';
SelfAssessedHealthStatus{87,1} = 'Poor';
SelfAssessedHealthStatus{88,1} = 'Good';
SelfAssessedHealthStatus{89,1} = 'Good';
SelfAssessedHealthStatus{90,1} = 'Good';
SelfAssessedHealthStatus{91,1} = 'Excellent';
SelfAssessedHealthStatus{92,1} = 'Excellent';
SelfAssessedHealthStatus{93,1} = 'Fair';
SelfAssessedHealthStatus{94,1} = 'Good';
SelfAssessedHealthStatus{95,1} = 'Excellent';
SelfAssessedHealthStatus{96,1} = 'Good';
SelfAssessedHealthStatus{97,1} = 'Good';
SelfAssessedHealthStatus{98,1} = 'Fair';
SelfAssessedHealthStatus{99,1} = 'Good';
SelfAssessedHealthStatus{100,1} = 'Fair';

Smoker = logical([1; 0; 0; 0; 0; 0; 1; 0; 0; 0; 0; 0; 0; 1; 0; 1; 1; 1; ...
                  0; 0; 0; 0; 0; 1; 1; 0; 0; 0; 0; 1; 1; 0; 0; 0; 0; 0; ...
                  1; 0; 1; 0; 1; 0; 1; 1; 0; 0; 0; 0; 0; 1; 1; 1; 1; 0; ...
                  1; 0; 0; 1; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 1; 0; 1; ...
                  0; 0; 1; 1; 0; 0; 0; 0; 0; 0; 1; 0; 0; 1; 1; 1; 1; 0; ...
                  1; 0; 0; 0; 0; 1; 1; 0; 1; 0]);

Systolic = [124; 109; 125; 117; 122; 121; 130; 115; 115; 118; 114; 115; ...
            127; 130; 114; 130; 124; 123; 119; 125; 121; 123; 114; 128; ...
            129; 114; 113; 125; 120; 127; 134; 121; 115; 127; 121; 127; ...
            136; 117; 124; 120; 128; 116; 132; 137; 117; 116; 119; 123; ...
            116; 124; 129; 130; 132; 117; 129; 118; 120; 138; 117; 113; ...
            122; 115; 120; 117; 123; 123; 119; 110; 121; 138; 125; 122; ...
            120; 117; 125; 124; 121; 118; 120; 118; 118; 122; 134; 131; ...
            113; 125; 135; 128; 123; 122; 138; 124; 130; 123; 129; 128; ...
            124; 119; 136; 114];

Weight = [176; 163; 131; 133; 119; 142; 142; 180; 183; 132; 128; 137; 174; ...
          202; 129; 181; 191; 131; 179; 172; 133; 117; 137; 146; 123; 189; ...
          143; 114; 166; 186; 126; 137; 138; 187; 193; 137; 192; 118; 180; ...
          128; 164; 183; 169; 194; 172; 135; 182; 121; 158; 179; 170; 136; ...
          135; 147; 186; 124; 134; 170; 180; 130; 130; 127; 141; 111; 134; ...
          189; 137; 136; 130; 137; 186; 127; 176; 127; 115; 178; 131; 183; ...
          194; 126; 186; 188; 189; 120; 132; 182; 120; 123; 141; 129; 184; ...
          181; 124; 174; 134; 171; 188; 186; 172; 177];

ans = saveVarsMat.ans; % <1x1 table> unsupported class

clear saveVarsMat;
